force-app/main/default/objects/Case_Email__c/Case_Email__c.object-meta.xml
<CustomObject>
    <label>Case Email</label>
    <nameField>
        <label>Case Email Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Email__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Emails</relationshipLabel>
    <relationshipName>Case_Emails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Email__c/fields/Case_Email_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Email_Number__c</fullName>
    <displayFormat>CE-{0000000}</displayFormat>
    <label>Case Email Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Case_Email__c/fields/Case_Id__c.field-meta.xml
<CustomField>
    <fullName>Case_Id__c</fullName>
    <label>Case Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Email__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <label>Case Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Email__c/fields/Email_Message_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Email_Message_Created_Date__c</fullName>
    <label>Email Message Created Date</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Email__c/fields/Email_Message_SharePoint_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Message_SharePoint_Id__c</fullName>
    <externalId>true</externalId>
    <label>Email Message SharePoint Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Email__c/fields/EmailMessage_Id__c.field-meta.xml
<CustomField>
    <fullName>EmailMessage_Id__c</fullName>
    <label>EmailMessage Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Email__c/fields/Files_SP_Id__c.field-meta.xml
<CustomField>
    <fullName>Files_SP_Id__c</fullName>
    <externalId>true</externalId>
    <label>Files SP Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GetFilesUsingSharepointId.cls
public class GetFilesUsingSharepointId {
    
    
    @AuraEnabled(cacheable=true) 
    public static List<Map<String, String>> getSharepointId(String parentCaseId){
               List<Map<String, String>> csvInfoList = new List<Map<String, String>>();

        //List<id> csvSPID=new List<id>();
        List<Case_Email__c> caseEmailList=[Select Id, OwnerId, IsDeleted, Name, CreatedDate, CreatedById, LastModifiedDate, 
                                           LastModifiedById, SystemModstamp, LastActivityDate, LastViewedDate, 
                                           LastReferencedDate, Case__c, Case_Email_Number__c, Case_Number__c, EmailMessage_Id__c, 
                                           Email_Message_SharePoint_Id__c,Files_SP_Id__c, Email_Message_Created_Date__c, Case_Id__c 
                                           from Case_Email__c where Case_Id__c =: parentCaseId];
        
        if(!caseEmailList.isEmpty()){
        System.debug('List<Case_Email__c> caseEmailList='+caseEmailList);
        for(Case_Email__c ce:caseEmailList){
            string sharepointid=ce.Files_SP_Id__c;
            System.debug('string sharepointid='+sharepointid);
            //csvSPID.add(sharepointid);
            //System.debug('List<id> csvSPID='+csvSPID);            
            
            
     
                HttpRequest req = new HttpRequest();
                req.setMethod('GET');
                req.setHeader('Accept', 'application/json;odata=verbose');
                req.setEndpoint('callout:Sharepoint/v1.0/drives/b!3RPB15XxtkSn_wJ9OGDxDwymYO9ecrFLrZXuL7fJXMpOcHHo4EI6TZMW56RJH70a/items/' + sharepointid + '/content');
                HTTPResponse res = new Http().send(req);
                try{
                    while (res.getStatusCode() == 302) {
                        req.setEndpoint(res.getHeader('Location'));
                        res = new Http().send(req);
                    }
                }catch(exception o){
                    System.debug('Catch exception1'+o.getMessage());
                }

                Blob headerValue= blob.valueOf(res.getBody());
            
            String body = EncodingUtil.base64Encode(headerValue);
            
            String lines = res.getBody();
            System.debug('Content after printing body:'+lines);
           
        }
        }
                return csvInfoList;
        
    }
    
    @AuraEnabled
    public static void getEmailData(String emailMessageId){
        emailMessageId = emailMessageId.right(19).left(18);
        system.debug('message id '+emailMessageId);
        Case_Email__c caseEmail = [Select Id, OwnerId, IsDeleted, Name, CreatedDate, CreatedById, LastModifiedDate, 
                                           LastModifiedById, SystemModstamp, LastActivityDate, LastViewedDate, 
                                           LastReferencedDate, Case__c, Case_Email_Number__c, Case_Number__c, EmailMessage_Id__c, 
                                           Email_Message_SharePoint_Id__c, Email_Message_Created_Date__c, Case_Id__c 
                                           from Case_Email__c where EmailMessage_Id__c =: emailMessageId limit 1];
        string sharepointid = caseEmail.Email_Message_SharePoint_Id__c;
            System.debug('string sharepointid='+sharepointid);
            //csvSPID.add(sharepointid);
            //System.debug('List<id> csvSPID='+csvSPID);            
            
                HttpRequest req = new HttpRequest();
                req.setMethod('GET');
                req.setHeader('Accept', 'application/json;odata=verbose');
                req.setEndpoint('callout:Sharepoint/v1.0/drives/b!3RPB15XxtkSn_wJ9OGDxDwymYO9ecrFLrZXuL7fJXMpOcHHo4EI6TZMW56RJH70a/items/' + sharepointid + '/content');
                HTTPResponse res = new Http().send(req);
                try{
                    while (res.getStatusCode() == 302) {
                        req.setEndpoint(res.getHeader('Location'));
                        res = new Http().send(req);
                    }
                }catch(exception o){
                    System.debug('Catch exception1'+o.getMessage());
                }

       Blob headerValue= blob.valueOf(res.getBody());
            
            String body = EncodingUtil.base64Encode(headerValue);
            
            String lines = res.getBody();
           
       
    }
}