force-app/main/default/objects/Case_Email__c/Case_Email__c.object-meta.xml
<CustomObject>
    <label>Case Email</label>
    <nameField>
        <label>Case Email Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Email__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Emails</relationshipLabel>
    <relationshipName>Case_Emails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Email__c/fields/Case_Email_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Email_Number__c</fullName>
    <displayFormat>CE-{0000000}</displayFormat>
    <label>Case Email Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Case_Email__c/fields/Case_Id__c.field-meta.xml
<CustomField>
    <fullName>Case_Id__c</fullName>
    <label>Case Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Email__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <label>Case Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Email__c/fields/EM_Sharepoint_Web_Url__c.field-meta.xml
<CustomField>
    <fullName>EM_Sharepoint_Web_Url__c</fullName>
    <label>EM Sharepoint Web Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Case_Email__c/fields/Email_Message_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Email_Message_Created_Date__c</fullName>
    <label>Email Message Created Date</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Email__c/fields/Email_Message_SharePoint_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Message_SharePoint_Id__c</fullName>
    <externalId>true</externalId>
    <label>Email Message SharePoint Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Email__c/fields/Email_Message_SP_Folder_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Message_SP_Folder_Id__c</fullName>
    <externalId>true</externalId>
    <label>Email Message SP Folder Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Email__c/fields/Email_Message_Subject__c.field-meta.xml
<CustomField>
    <fullName>Email_Message_Subject__c</fullName>
    <label>Email Message Subject</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case_Email__c/fields/EmailMessage_Id__c.field-meta.xml
<CustomField>
    <fullName>EmailMessage_Id__c</fullName>
    <label>EmailMessage Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Email__c/fields/Files_Share_Point_Id__c.field-meta.xml
<CustomField>
    <fullName>Files_Share_Point_Id__c</fullName>
    <label>Files Share Point Id</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case_Email__c/fields/Files_SP_Id__c.field-meta.xml
<CustomField>
    <fullName>Files_SP_Id__c</fullName>
    <externalId>true</externalId>
    <label>Files SP Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DeleteButtonFunctV1.cls
public class DeleteButtonFunctV1 {
    Public static void deleteSharepointId(String fileSharepointId){
        /*List<Case_Email__c> caseEmailList=[select Id, OwnerId, IsDeleted, Name, CreatedDate, CreatedById, LastModifiedDate, LastModifiedById, SystemModstamp, 
                                           LastActivityDate, LastViewedDate, LastReferencedDate, Case__c, Case_Email_Number__c, Case_Number__c, EmailMessage_Id__c, 
                                           Email_Message_SharePoint_Id__c, Email_Message_Created_Date__c, Case_Id__c, Email_Message_Subject__c, EM_Sharepoint_Web_Url__c, 
                                           Email_Message_SP_Folder_Id__c, Files_SP_Id__c, Files_Share_Point_Id__c from Case_Email__c  where Files_Share_Point_Id__c =: fileSharepointIdsp limit 1];
        */
        //String fileSharepointId;
        try{
            	   //fileSharepointId=caseEmailList[0].Files_Share_Point_Id__c;
            	   //fileSharepointId='01SCG6PXPNIAXL3OCS5RALIQIBCLEKFFOD';
            //System.debug('Each files sharepointID==> ' +fileSharepointId);
            String driveId = 'b!3RPB15XxtkSn_wJ9OGDxDwymYO9ecrFLrZXuL7fJXMpOcHHo4EI6TZMW56RJH70a';
            string siteId='d7c113dd-f195-44b6-a7ff-027d3860f10f';

            
            Http httpCallout = new Http();
            HttpRequest req = new HttpRequest();
            
            
            req.setEndpoint('callout:Sharepoint/v1.0/sites/' + siteId + '/drives/' + driveId + '/items/' + fileSharepointId); 
            
            req.setMethod('DELETE');
            req.setHeader('Content-Type', 'application/json');
            req.setHeader('Accept', 'application/json');
            //req.setBodyAsBlob(fileBody);
            
            HTTPResponse res = httpCallout.send(req);
            System.debug('HTTPResponse respomse status code==> '+res.getStatusCode());
            if(res.getStatusCode() == 204){
                System.debug('File is deleted');
            }else{
                System.debug('There is a problem in calss.');
            }           
            
        }catch(Exception e){
                System.debug('Catch Exception==> '+e.getMessage());
            }
        
    }
    
}