force-app/main/default/objects/Staging__b/Staging__b.object-meta.xml
<CustomObject>
    <label>Staging</label>
    <pluralLabel>Staging</pluralLabel>
</CustomObject>

force-app/main/default/objects/Staging__b/fields/Chunk__c.field-meta.xml
<CustomField>
    <fullName>Chunk__c</fullName>
    <label>Chunk</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staging__b/fields/Content_Version_Id__c.field-meta.xml
<CustomField>
    <fullName>Content_Version_Id__c</fullName>
    <label>Content Version Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staging__b/fields/From_sObject__c.field-meta.xml
<CustomField>
    <fullName>From_sObject__c</fullName>
    <label>From sObject</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staging__b/fields/Job_ID__c.field-meta.xml
<CustomField>
    <fullName>Job_ID__c</fullName>
    <label>Job ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staging__b/fields/Linked_Entity_Id__c.field-meta.xml
<CustomField>
    <fullName>Linked_Entity_Id__c</fullName>
    <label>Linked Entity Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staging__b/fields/sObject__c.field-meta.xml
<CustomField>
    <fullName>sObject__c</fullName>
    <label>sObject</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staging__b/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CheckClassApiFutureClass.cls
public class CheckClassApiFutureClass {

    public static void checkId(){
        List<Staging__b> stagingList = [select sObject__c, Chunk__c, Linked_Entity_Id__c, Content_Document_Id__c, Content_Version_Id__c, Status__c, Job_ID__c, Title__c, From_sObject__c
                                            from Staging__b
                                            where Status__c = 'Not Started'];
        
        string  stagingId;
        
        for(Staging__b stb:stagingList){
            stagingId=stb.Chunk__c;
        }                                
                                        
       // ApiFutureCalling.fileMigration(stagingId);
        
        ApiFutureCalling api=new ApiFutureCalling();
      //  string fileSharePointId=api.fileMigration.eachItem.id;
      //  system.debug(' ApiFutureCalling.fileMigration' +fileSharePointId);
    }
}