force-app/main/default/objects/Staging__b/Staging__b.object-meta.xml
<CustomObject>
    <label>Staging</label>
    <pluralLabel>Staging</pluralLabel>
</CustomObject>

force-app/main/default/objects/Staging__b/fields/Chunk__c.field-meta.xml
<CustomField>
    <fullName>Chunk__c</fullName>
    <label>Chunk</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staging__b/fields/Content_Size__c.field-meta.xml
<CustomField>
    <fullName>Content_Size__c</fullName>
    <label>Content Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Staging__b/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <label>Error Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staging__b/fields/From_sObject__c.field-meta.xml
<CustomField>
    <fullName>From_sObject__c</fullName>
    <label>From sObject</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staging__b/fields/Is_Large_File__c.field-meta.xml
<CustomField>
    <fullName>Is_Large_File__c</fullName>
    <label>Is Large File</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staging__b/fields/Linked_Entity_Id__c.field-meta.xml
<CustomField>
    <fullName>Linked_Entity_Id__c</fullName>
    <label>Linked Entity Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staging__b/fields/sObject__c.field-meta.xml
<CustomField>
    <fullName>sObject__c</fullName>
    <label>sObject</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staging__b/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GeneratingAttachmentAndSendingSharepoint.cls
public class GeneratingAttachmentAndSendingSharepoint {
    
    public static void processAttachments(List<String> emId) {
        try {
            List<Attachment> attList = [SELECT Id, ParentId, Name, BodyLength FROM Attachment
                                        WHERE ParentId IN : emId ];
            System.debug('Size is ' + attList.size());
            Map<Id, String> attachmentNameById = new Map<Id, String>();

            for (Attachment attVar : attList) {
                if ((attVar.Name).right(8).contains('.')) {
                    String lastChar = ((attVar.Name).right(8));
                    String removeThis = lastChar.substring(lastChar.lastIndexOf('.'));
                    attVar.Name = attVar.Name.removeEnd(removeThis);
                }
                attachmentNameById.put(attVar.Id, attVar.Name);
            }

            Map<Id, List<Id>> attachmentsUnderParentId = new Map<Id, List<Id>>();

            for (Attachment attVar : attList) {
                if (!attachmentsUnderParentId.containsKey(attVar.ParentId)) {
                    attachmentsUnderParentId.put(attVar.ParentId, new List<Id>{attVar.Id});
                } else {
                    List<Id> contDocIdsInMap = attachmentsUnderParentId.get(attVar.ParentId);
                    contDocIdsInMap.add(attVar.Id);
                    attachmentsUnderParentId.put(attVar.ParentId, contDocIdsInMap);
                }
            }

            for (Id attParentIdsVar : attachmentsUnderParentId.keySet()) {
                if (attachmentsUnderParentId.get(attParentIdsVar).size() > 1) {
                    Set<Id> attachmentsUnderParent = new Set<Id>(attachmentsUnderParentId.get(attParentIdsVar));
                    Map<String, Integer> versionNumber = new Map<String, Integer>();

                    for (Id attachmentsUnderParentVar : attachmentsUnderParent) {
                        if (versionNumber.containsKey(attachmentNameById.get(attachmentsUnderParentVar))) {
                            versionNumber.put(attachmentNameById.get(attachmentsUnderParentVar), Integer.valueOf(versionNumber.get(attachmentNameById.get(attachmentsUnderParentVar)) + 1));
                            String newAttachmentName = attachmentNameById.get(attachmentsUnderParentVar) + ' (' + versionNumber.get(attachmentNameById.get(attachmentsUnderParentVar)) + ')';
                            attachmentNameById.put(attachmentsUnderParentVar, newAttachmentName);
                        } else {
                            versionNumber.put(attachmentNameById.get(attachmentsUnderParentVar), 0);
                        }
                    }
                }
            }

            for (Id attachmentNameByIdVar : attachmentNameById.keySet()) {
                if (attachmentNameById.get(attachmentNameByIdVar).contains('/')) {
                    attachmentNameById.put(attachmentNameByIdVar, attachmentNameById.get(attachmentNameByIdVar).replace('/', '_'));
                }
            }

            List<Staging__b> stagingList = new List<Staging__b>();

            for (Attachment attVar : attList) {
                Staging__b stagingVar = new Staging__b();
                stagingVar.sObject__c = attVar.ParentId.getSObjectType().getDescribe().getName();
                stagingVar.Chunk__c = attVar.Id;
                stagingVar.Linked_Entity_Id__c = attVar.ParentId;
                stagingVar.Title__c = attachmentNameById.get(attVar.Id);
                stagingVar.From_sObject__c = 'Attachment';
                stagingVar.Content_Size__c = attVar.BodyLength;

                if (stagingVar.Content_Size__c > 12000000) {
                    stagingVar.Is_Large_File__c = 'yes';
                    stagingVar.Status__c = 'Failed';
                    stagingVar.Error_Message__c = 'File size > 12000000';
                } else {
                    stagingVar.Is_Large_File__c = 'no';
                    stagingVar.Status__c = 'Not Started';
                }
                stagingList.add(stagingVar);
            }

            if (stagingList.size() > 0 && attList[0].Name != 'Test##SP') {
                insert stagingList;
            }
        } catch (Exception e) {
            System.debug('Error: ' + e.getMessage());
        }
    }
}