force-app/main/default/objects/EmailMessage_Html__b/EmailMessage_Html__b.object-meta.xml
<CustomObject>
    <label>EmailMessage Html</label>
    <pluralLabel>EmailMessage Htmls</pluralLabel>
</CustomObject>

force-app/main/default/objects/EmailMessage_Html__b/fields/EmailMessage_Id__c.field-meta.xml
<CustomField>
    <fullName>EmailMessage_Id__c</fullName>
    <label>EmailMessage Id</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EmailMessage_Html__b/fields/sObject__c.field-meta.xml
<CustomField>
    <fullName>sObject__c</fullName>
    <label>sObject</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EmailMessage_Html__b/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UploadSharePoint.cls
Public class UploadSharePoint{
    
    
}


/*
public with sharing class UploadSharePoint implements Database.Batchable<sObject>{
    
    String Status;
    public List<EmailMessage_Html__b> start(Database.BatchableContext BC) {
        return [select EmailMessage_Id__c,Status__c,sObject__c from EmailMessage_Html__b where Status__c =: status limit 500];
        //System.debug('res.getStatusCode()=>' +res.getStatusCode());
    }
    
    public void execute(Database.BatchableContext BC, List<EmailMessage_Html__b> emList){
        
        for(EmailMessage_Html__b emhb:emList){
            string chunkid = emhb.Emailmessage_Id__c;
            SendCSVtoSharepointDK.fileMigration(chunkid);
        }
        
      //  SendCSVtoSharepointDK.fileMigration(stagingId);
        
        
    }
    
    public void finish(Database.BatchableContext BC){
       System.debug('Batch Is Completed');
    }
    
}
*/