force-app/main/default/objects/EmailMessage_Html__b/EmailMessage_Html__b.object-meta.xml
<CustomObject>
    <label>EmailMessage Html</label>
    <pluralLabel>EmailMessage Htmls</pluralLabel>
</CustomObject>

force-app/main/default/objects/EmailMessage_Html__b/fields/EmailMessage_Id__c.field-meta.xml
<CustomField>
    <fullName>EmailMessage_Id__c</fullName>
    <label>EmailMessage Id</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EmailMessage_Html__b/fields/sObject__c.field-meta.xml
<CustomField>
    <fullName>sObject__c</fullName>
    <label>sObject</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EmailMessage_Html__b/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HtmlCleanerwithID.cls
global class HtmlCleanerwithID implements
Database.Batchable<SObject> {
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        String emId = '02sVE000000gCCtYAM';
        return Database.getQueryLocator([
            SELECT EmailMessage_Id__c, Status__c, sObject__c 
            FROM EmailMessage_Html__b 
            WHERE EmailMessage_Id__c = :emId 
            AND Status__c = 'Not Started' 
            AND sObject__c = 'Email Message'
        ]);
    }    
    global void execute(Database.BatchableContext bc, List<sObject> scope){
                Database.deleteImmediate(scope);
        
    }
    
    global void finish(Database.BatchableContext bc){
        System.debug('HtmlCleanerwithID is successfully completed.');
    }
     
}