force-app/main/default/objects/EmailMessageHtml__c/EmailMessageHtml__c.object-meta.xml
<CustomObject>
    <label>EmailMessageHtml</label>
    <nameField>
        <label>EmailMessage Html</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EmailMessageHtmls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EmailMessageHtml__c/fields/Csv_Body__c.field-meta.xml
<CustomField>
    <fullName>Csv_Body__c</fullName>
    <label>Csv Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EmailMessageHtml__c/fields/EmailMessage_Id__c.field-meta.xml
<CustomField>
    <fullName>EmailMessage_Id__c</fullName>
    <label>EmailMessage Id</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EmailMessageHtml__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <label>Error Message</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EmailMessageHtml__c/fields/File_Body__c.field-meta.xml
<CustomField>
    <fullName>File_Body__c</fullName>
    <label>File Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EmailMessageHtml__c/fields/File_Size__c.field-meta.xml
<CustomField>
    <fullName>File_Size__c</fullName>
    <label>File Size</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EmailMessageHtml__c/fields/Is_Large_File__c.field-meta.xml
<CustomField>
    <fullName>Is_Large_File__c</fullName>
    <label>Is Large File</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EmailMessageHtml__c/fields/Job_ID__c.field-meta.xml
<CustomField>
    <fullName>Job_ID__c</fullName>
    <label>Job ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EmailMessageHtml__c/fields/Parent_Case_Id__c.field-meta.xml
<CustomField>
    <fullName>Parent_Case_Id__c</fullName>
    <description>Email message parent case id</description>
    <label>Parent Case Id</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EmailMessageHtml__c/fields/sObject__c.field-meta.xml
<CustomField>
    <fullName>sObject__c</fullName>
    <label>sObject</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purge_Case__c/Purge_Case__c.object-meta.xml
<CustomObject>
    <label>Purge_Case</label>
    <nameField>
        <displayFormat>PC-{000000000}</displayFormat>
        <label>Purge Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purge_Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purge_Case__c/fields/EmailMessage_Id__c.field-meta.xml
<CustomField>
    <fullName>EmailMessage_Id__c</fullName>
    <label>EmailMessage Id</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/PurgeCaseEmailsSK.cls
global class PurgeCaseEmailsSK implements Database.Batchable<SObject>, Database.Stateful {
 
    global List<EmailMessageHtml__c> listEmailHtmls;
    global PurgeCaseEmailsSK(List<EmailMessageHtml__c> listEmailHtmls){
        this.listEmailHtmls=listEmailHtmls;
    }
    global List<EmailMessageHtml__c> start(Database.BatchableContext BC) {
       //List<EmailMessageHtml__c> listEmailHtmls=[select Id, Name, Csv_Body__c, EmailMessage_Id__c, Error_Message__c, File_Body__c, File_Size__c, Is_Large_File__c, Job_ID__c, Parent_Case_Id__c, sObject__c, Status__c, Title__c from EmailMessageHtml__c where Status__c='Not Started'];
       return listEmailHtmls;
       
    }
 
   
    global void execute(Database.BatchableContext BC, List<EmailMessageHtml__c> scope) {
         /*Map<String,List<String>> MapingCaseIdWithEmailId=new  Map<String,List<String>>();
       
        for(EmailMessageHtml__c emHtRec:scope){
         if (MapingCaseIdWithEmailId.containsKey(emHtRec.Parent_Case_Id__c)) {
        List<String>emailIds = MapingCaseIdWithEmailId.get(emHtRec.Parent_Case_Id__c);
        emailIds.add(emHtRec.EmailMessage_Id__c);
        MapingCaseIdWithEmailId.put(emHtRec.Parent_Case_Id__c, emailIds);
       }
            else 
       {
    List<String> emailIds = new List<String>();
    emailIds.add(emHtRec.EmailMessage_Id__c);  
    MapingCaseIdWithEmailId.put(emHtRec.Parent_Case_Id__c, emailIds);  
		}
      }
        Set<String> caseIdKeys =MapingCaseIdWithEmailId.keySet();


       List<String> caseIdKeyList = new List<String>(caseIdKeys);
        List<Purge_Case__c> lispurgeCase=new List<Purge_Case__c>();
        for(integer i=0;i<MapingCaseIdWithEmailId.keySet().size();i++){
             Purge_Case__c P=new Purge_Case__c();
             P.Case_Id__c=caseIdKeyList[i];
             List<String>emIds=MapingCaseIdWithEmailId.get(caseIdKeyList[i]);
            p.EmailMessage_Id__c=String.join(emIds, ',\n');
            p.Status__c='Ready to Upload';
            lispurgeCase.add(p);
            System.debug('Email Id is:'+p.EmailMessage_Id__c);
            System.debug('XCase Id is:'+p.Case_Id__c);
        }
        System.debug('List of values to insert:'+lispurgeCase);
        System.debug('Map Values are :'+MapingCaseIdWithEmailId);
        insert lispurgeCase;
       
        */
        
    }
 
   
    global void finish(Database.BatchableContext BC) {
       
}
}