force-app/main/default/objects/EmailMessageHtml__c/EmailMessageHtml__c.object-meta.xml
<CustomObject>
    <label>EmailMessageHtml</label>
    <nameField>
        <label>EmailMessage Html</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EmailMessageHtmls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EmailMessageHtml__c/fields/EmailMessage_Id__c.field-meta.xml
<CustomField>
    <fullName>EmailMessage_Id__c</fullName>
    <label>EmailMessage Id</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EmailMessageHtml__c/fields/Parent_Case_Id__c.field-meta.xml
<CustomField>
    <fullName>Parent_Case_Id__c</fullName>
    <description>Email message parent case id</description>
    <label>Parent Case Id</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EmailMessageHtml__c/fields/Retry_Executed_Count__c.field-meta.xml
<CustomField>
    <fullName>Retry_Executed_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Retry Executed Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stagging__c/Stagging__c.object-meta.xml
<CustomObject>
    <label>Stagging</label>
    <nameField>
        <label>Stagging Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stagging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stagging__c/fields/Chunk__c.field-meta.xml
<CustomField>
    <fullName>Chunk__c</fullName>
    <label>Chunk</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Arch_UploadSecondValidationDK_V1.cls
global class Arch_UploadSecondValidationDK_V1 implements Database.Batchable<SObject> {
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'Select id, ParentId from EmailMessage where  Parent.CreatedDate =TODAY';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<EmailMessage> emailList) {
        Set<Id> emailId = new Set<Id>();
        Set<Id> caseSetId = new Set<Id>();
        String emailIdHtml;
        String emailCaseId;
        String emailIdStagging;
        for(EmailMessage emList : emailList){
            emailId.add(emList.Id);     
            caseSetId.add(emList.ParentId);
        }
        
        //List<EmailMessageHTML__c> emailHtmlList = [Select Id, EmailMessage_Id__c, Parent_Case_Id__c From EmailMessageHTML__c where Parent_Case_Id__c =: caseSetId];
        List<EmailMessageHTML__c> emailHtmlList = [Select Id, EmailMessage_Id__c, Parent_Case_Id__c From EmailMessageHTML__c where Retry_Executed_Count__c = 1];
        For(EmailMessageHTML__c emailHtml : emailHtmlList){
            emailIdHtml = emailHtml.Id;        
            emailCaseId = emailHtml.Parent_Case_Id__c;
        }
        
        
        
        //List<Stagging__c> staggingList = [Select id, Chunk__c, Content_Document_Id__c, Linked_Entity_Id__c From Stagging__c where Linked_entity_id__c =: emailId];
        List<Stagging__c> staggingList = [Select id, Chunk__c, Content_Document_Id__c, Linked_Entity_Id__c From Stagging__c where Retry_Executed_Count__c = 1];
        For(Stagging__c stagingEmailId : staggingList){
            emailIdStagging = stagingEmailId.Id;
        }
        

        
        //ID jobId = System.enqueueJob(new Arch_SharePointSecondCountQueue(parentcaseid,emailid,mapofIdAttachmentCount.get(emailid)));
        
    }
    
    global void finish(Database.BatchableContext BC) {
        
    }
    
}