force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <description>Potential or Existing Clients</description>
    <label>Client</label>
</RecordType>

force-app/main/default/objects/Case/fields/Failed_Record__c.field-meta.xml
<CustomField>
    <fullName>Failed_Record__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Failed Record</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Issue_with__c.field-meta.xml
<CustomField>
    <fullName>Issue_with__c</fullName>
    <label>Issue with</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stagging__c/Stagging__c.object-meta.xml
<CustomObject>
    <label>Stagging</label>
    <nameField>
        <label>Stagging Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stagging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stagging__c/fields/Upload_Failed__c.field-meta.xml
<CustomField>
    <fullName>Upload_Failed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Upload Failed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Arch_UploadValidationBatchSkTest.cls
@isTest
public class Arch_UploadValidationBatchSkTest {
	 public class MockHttpCallout implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HTTPResponse res = new HTTPResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody('{"value": [{"name": "File1"}, {"name": "File2"}]}');
            res.setStatusCode(200);
            return res;
        }
    }
    
    @isTest
    static void testBatchExecution() {
         Test.setMock(HttpCalloutMock.class, new MockHttpCallout());
       Account testAccount = new Account(Name = 'Test Account');
        insert testAccount;
        Contact con=new Contact(lastName='Sujatha',Email='suja@gmail.com',accountId=testAccount.id);
        insert con;
        Case cse = new Case(
            Subject = 'Test Case', 
            AccountId = testAccount.Id, 
            Failed_Record__c = False,
            Reason = 'Issue Resolved',
           	Status='New'
        );
        insert cse;
        cse.Status='Closed';
        cse.Reason='Duplicate';
        cse.ContactId=con.id;
        cse.Issue_with__c='Client';
        update cse;
      
        
        EmailMessage emailMessage = new EmailMessage(
            ParentId = cse.Id,
            FromAddress = 'test@example.com',
            ToAddress = 'recipient@example.com',
            HtmlBody = 'Test Email Body',
            Status = '3'
        );
        insert emailMessage;
        
        Stagging__c stagingRecord = new Stagging__c(
            Linked_Entity_Id__c = emailMessage.Id,
            Retry_Executed_Count__c = 1,
            Upload_Failed__c = false
        );
        insert stagingRecord;
        
        
        Attachment attach1 = new Attachment();   	
        attach1.Name = 'Test##SP';
        Blob bodyBlobAttach1 = Blob.valueOf('Unit Test Attachment Body');
        attach1.Body = bodyBlobAttach1;
        attach1.ParentId = emailMessage.Id;
        insert attach1;                
        
        ContentVersion content = new ContentVersion(); 
        content.Title = 'Test##SP'; 
        content.PathOnClient = '/' + content.Title + '.jpg'; 
        Blob bodyBlob = Blob.valueOf('Unit Test ContentVersion Body'); 
        content.VersionData = bodyBlob; 
        content.Origin = 'H';
        insert content;
        
        ContentDocumentLink contentlink = new ContentDocumentLink();
        contentlink.LinkedEntityId = emailMessage.Id;
        contentlink.ContentDocumentId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =: content.Id].ContentDocumentId;
        //contentlink.ShareType = 'I';
        contentlink.Visibility = 'AllUsers';
        insert contentlink;
        Test.startTest();
        Arch_UploadValidationBatchSk batchInstance = new Arch_UploadValidationBatchSk();
        ID batchJobId = Database.executeBatch(batchInstance);
        Test.stopTest();
    }
}