force-app/main/default/objects/Account/fields/File_Test__c.field-meta.xml
<CustomField>
    <fullName>File_Test__c</fullName>
    <label>File Test</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case_Email__c/Case_Email__c.object-meta.xml
<CustomObject>
    <label>Case Email</label>
    <nameField>
        <label>Case Email Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Email__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Emails</relationshipLabel>
    <relationshipName>Case_Emails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Email__c/fields/Case_Email_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Email_Number__c</fullName>
    <displayFormat>CE-{0000000}</displayFormat>
    <label>Case Email Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Case_Email__c/fields/Case_Id__c.field-meta.xml
<CustomField>
    <fullName>Case_Id__c</fullName>
    <label>Case Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Email__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <label>Case Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Email__c/fields/Email_Message_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Email_Message_Created_Date__c</fullName>
    <label>Email Message Created Date</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Email__c/fields/Email_Message_SharePoint_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Message_SharePoint_Id__c</fullName>
    <externalId>true</externalId>
    <label>Email Message SharePoint Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Email__c/fields/Email_Message_SP_Folder_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Message_SP_Folder_Id__c</fullName>
    <externalId>true</externalId>
    <label>Email Message SP Folder Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Email__c/fields/EmailMessage_Id__c.field-meta.xml
<CustomField>
    <fullName>EmailMessage_Id__c</fullName>
    <label>EmailMessage Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Email__c/fields/Files_SP_Id__c.field-meta.xml
<CustomField>
    <fullName>Files_SP_Id__c</fullName>
    <externalId>true</externalId>
    <label>Files SP Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FileSharepointTestDk1.cls
public class FileSharepointTestDk1{
    //@AuraEnabled
    public STRING getEmailFileData(String emailMessageId){
        //emailMessageId = emailMessageId.right(19).left(18);
        //system.debug('message id '+emailMessageId);
        Case_Email__c caseEmail = [Select Id, OwnerId, IsDeleted, Name, CreatedDate, CreatedById, LastModifiedDate, 
                                   LastModifiedById, SystemModstamp, LastActivityDate, LastViewedDate, 
                                   LastReferencedDate, Case__c, Case_Email_Number__c, Case_Number__c, EmailMessage_Id__c, 
                                   Email_Message_SharePoint_Id__c, Email_Message_Created_Date__c, Case_Id__c, Email_Message_SP_Folder_Id__c
                                   from Case_Email__c where EmailMessage_Id__c =: emailMessageId limit 1];
        String sharepointfileid = caseEmail.Files_SP_Id__c;
        System.debug('string sharepointfileid='+sharepointfileid);
        
        List<Account> accList=[Select id,name,Description,File_Test__c from account where id='001VE000007msGcYAI'];

        //csvSPID.add(sharepointid);
        //System.debug('List<id> csvSPID='+csvSPID);            
        Blob headerValue;
        String body;
        String lines;
        Map<String, String> fileInfo = new Map<String, String>();    
        try{
            HttpRequest req = new HttpRequest();
            req.setMethod('GET');
            req.setHeader('Accept', 'application/json;odata=verbose');
            req.setEndpoint('callout:Sharepoint/v1.0/drives/b!3RPB15XxtkSn_wJ9OGDxDwymYO9ecrFLrZXuL7fJXMpOcHHo4EI6TZMW56RJH70a/items/'+sharepointfileid+'/content');
            HTTPResponse res = new Http().send(req);
            try{
                while (res.getStatusCode() == 302) {
                    req.setEndpoint(res.getHeader('Location'));
                    res = new Http().send(req);
                }
            }catch(exception o){
                System.debug('Catch exception1'+o.getMessage());
            }
            
             headerValue= blob.valueOf(res.getBody());
            
             body = EncodingUtil.base64Encode(headerValue);
            
             lines = res.getBody();
            System.debug('headerValue'+headerValue);
            System.debug('body'+body);
            System.debug('lines'+lines);
            
            //system.debug('csv returned '+csvInfo);
            //return csvInfo;
            
            for(Account acc:accList){
                acc.Description=body;
                acc.File_Test__c=body;
            }
            update accList;
        }catch(exception p){
            System.debug('Catch exception1'+p.getMessage());
        }
        //return headerValue;
        return body;
        //return lines;

        
     }
}