force-app/main/default/objects/CampaignMember/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Campaign Status</label>
    <length>65</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Login__c/Error_Login__c.object-meta.xml
<CustomObject>
    <label>Error Login</label>
    <nameField>
        <displayFormat>EL-{0000}</displayFormat>
        <label>Error Login Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logins</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Login__c/fields/Error_Cause__c.field-meta.xml
<CustomField>
    <fullName>Error_Cause__c</fullName>
    <label>Error Cause</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Login__c/fields/Error_LineNumber__c.field-meta.xml
<CustomField>
    <fullName>Error_LineNumber__c</fullName>
    <label>Error LineNumber</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Error_Login__c/fields/Error_StackTraceString__c.field-meta.xml
<CustomField>
    <fullName>Error_StackTraceString__c</fullName>
    <label>Error StackTraceString</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Error_Login__c/fields/Error_TypeName__c.field-meta.xml
<CustomField>
    <fullName>Error_TypeName__c</fullName>
    <label>Error TypeName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UpdateCampaignMembersQueuable.cls
public with sharing class UpdateCampaignMembersQueuable implements Queueable {
    List<CampaignMember> listOfCampaignMembersToBeUpdated;
    public class CustomException extends exception {}
    
    public UpdateCampaignMembersQueuable() {
        listOfCampaignMembersToBeUpdated = new List<CampaignMember>();
    }
    
    public UpdateCampaignMembersQueuable(List<CampaignMember> listOfCampaignMembers) {
        this();
        this.listOfCampaignMembersToBeUpdated = listOfCampaignMembers;
    }
    
    public void execute(QueueableContext context) {
        for(CampaignMember eachCampaignMember :listOfCampaignMembersToBeUpdated){
            eachCampaignMember.Status__c = 'Activate';
        }
        try{
            update listOfCampaignMembersToBeUpdated;
            if(CampaignTriggerHandlerTest.isTestFailInsert){
                throw new CustomException('Fail the test class!');
            }
        }
        catch(exception e)
        {
            system.debug('exception e is '+e.getMessage());
            //Declare the List to hold the Error_Login__c
            List<Error_Login__c> listOfErrorLogin = new List<Error_Login__c>();
            Error_Login__c eachErrorlogin = new Error_Login__c();
            eachErrorlogin.Error_LineNumber__c = e.getLineNumber();
            eachErrorlogin.Error_Message__c = e.getMessage();
            eachErrorlogin.Error_StackTraceString__c = e.getStackTraceString();
            eachErrorlogin.Error_TypeName__c = e.getTypeName();
            eachErrorlogin.Error_Cause__c	= string.valueof(e.getCause());
            listOfErrorLogin.add(eachErrorlogin);
            
            insert listOfErrorLogin;
        }
    }
    
}