force-app/main/default/objects/GetDataFromSharepoint__e/GetDataFromSharepoint__e.object-meta.xml
<CustomObject>
    <label>GetDataFromSharepoint</label>
    <pluralLabel>GetDataFromSharepoints</pluralLabel>
</CustomObject>

force-app/main/default/objects/GetDataFromSharepoint__e/fields/Emailid__c.field-meta.xml
<CustomField>
    <fullName>Emailid__c</fullName>
    <label>Emailid</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/GetDataFromSharepoint__e/fields/ParentCaseId__c.field-meta.xml
<CustomField>
    <fullName>ParentCaseId__c</fullName>
    <label>ParentCaseId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GetFileUsingCaseSPId_V1Test_V2.cls
@isTest
public class GetFileUsingCaseSPId_V1Test_V2 {
    @isTest
    static void testTriggerExecution() {
        Case testCase = new Case(Subject = 'Test Case');
        insert testCase;
        
        List<GetDataFromSharepoint__e> events = new List<GetDataFromSharepoint__e>();
        events.add(new GetDataFromSharepoint__e(Emailid__c = '02s567897657843', ParentCaseId__c = testCase.Id));
        events.add(new GetDataFromSharepoint__e(Emailid__c = '02s23456789ijhf', ParentCaseId__c = testCase.Id));
        
        Test.startTest();
        EventBus.publish(events);
        Test.stopTest();
        
        
        GetFileUsingCaseSPId_V1.getCaseFolderData(testCase.id);
    }
    
    
}